// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idpycvkpnseqzgzbzsmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkcHljdmtwbnNlcXpnemJ6c211Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNDgzODUsImV4cCI6MjA2ODcyNDM4NX0.y7zoNxEvbL07ji_rm0i8bCF5SXxqXmdfzOta5tPL0MM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});